services:
  ci:
    image: ci
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    networks:
      - back-tier
    environment:
      - MONGODB_URL=mongodb://root:rootpasswd@mongo:27017/mydb
      - REDIS_URL=redis://redis:6379

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpasswd
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - back-tier

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --bind redis --port 6379 --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - back-tier

  local-mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpasswd
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
      - ./db:/docker-entrypoint-initdb.d:ro

  local-redis:
    restart: always
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

networks:
  back-tier:

volumes:
  caddy_data:
  caddy_config:
  mongo-data:
  redis-data:
