services:
  ci:
    image: ci
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    links:
      - redis
    depends_on:
      - redis
    networks:
      - back-tier
    environment:
      - REDIS_URL=redis://redis:6379

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --bind redis --port 6379 --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - back-tier

  local-redis:
    restart: always
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

networks:
  back-tier:

volumes:
  caddy_data:
  caddy_config:
  redis-data:
