version: '3.9'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/fastify-starter
    tty: true

  ci:
    image: ci
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
