version: '3.9'

services:
  ci:
    image: ci
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true

  app:
    image: app
    build:
      context: .
      dockerfile: .circleci/Dockerfile
    ports:
      - 3000:3000

  server:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .circleci/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  caddy_data:
  caddy_config:
  redis-data:
