services:
  - type: web
    name: fastify-starter
    region: oregon
    plan: free
    branch: main
    env: node
    envVars:
      - key: NODE_VERSION
        value: 18.16.1
      - key: HOST
        value: 0.0.0.0
      - key: SITE_URL
        value: false
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SMTP_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    buildCommand: pnpm build
    startCommand: node dist/main.mjs
    healthCheckPath: /api/healthz
