services:
  - type: web
    name: fastify-starter
    runtime: node
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: SITE_URL
        value: onrender.com
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SMTP_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
    buildCommand: pnpm install; pnpm build
    startCommand: node dist/main.js
    healthCheckPath: /api/healthz
