services:
  - name: fastify-starter
    type: web
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/healthz

    dockerfilePath: ./.github/registry/Dockerfile

    envVars:
      - key: SITE_URL
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SMTP_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true

  # - name: fastify-starter-worker
  #   type: worker
  #   runtime: docker
  #   plan: starter
  #   region: oregon
  #   branch: main

  #   dockerfilePath: ./.github/registry/worker.Dockerfile

  #   envVars:
  #     - key: REDIS_URL
  #       sync: false
