services:
  - name: fastify-starter
    type: web
    runtime: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/healthz

    dockerfilePath: ./infra/Dockerfile

    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: SITE_URL
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SMTP_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true

  # - type: worker
  #   name: fastify-starter-queue
  #   runtime: node
  #   region: oregon
  #   plan: starter
  #   branch: main
  #   envVars:
  #     - key: NODE_VERSION
  #       value: 20.12.2
  #     - key: REDIS_URL
  #       sync: false
  #   buildCommand: pnpm install; pnpm build
  #   startCommand: node app/dist/worker.js
