services:
  - type: web
    name: fastify-starter
    region: oregon
    plan: free
    branch: main
    env: node
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - key: SITE_URL
        value: onrender.com
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: node dist/main.mjs
