version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build:
    working_directory: ~/fastify-starter
    executor: docker/default
    steps:
      - run: docker-compose up -d ci
      - run: docker-compose exec ci pnpm build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    steps:
      - attach_workspace:
          at: .
      - run: docker-compose exec ci pnpm lint
      - run: docker-compose exec ci pnpm unit

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
