version: 2.1

executors:
  flow-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/fastify-starter

jobs:
  build:
    executor: flow-executor/docker
    steps:
      - run: docker-compose up -d ci
      - run: docker-compose exec ci pnpm build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    steps:
      - attach_workspace:
          at: .
      - run: docker-compose exec ci pnpm lint
      - run: docker-compose exec ci pnpm unit

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
