name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
      - release
      - prod

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Trigger deployment
        run: curl -k ${{ secrets.DEPLOY_HOOK }}
