name: CD

on:
  push:
    branches:
      - main
      - release
      - prod

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: ./.github/workflows/ci.yaml
      - name: Trigger deployment
        run: curl -k ${{ secrets.DEPLOY_HOOK }}
